language: node_js
node_js: '10'
os:
  - windows

cache:
  directories:
    - node_modules
    - $HOME/.cache/electron

install:
  - npm install
  - npm update

script:
  - npm run lint
  - npm run make

after_success:
  - npm run publish --auth-token=$REPO_TOKEN
